apiVersion: v1
kind: Pod
metadata:
name: test-nginx
namespace: shujubu
labels:
name: test-nginx
spec:
containers:

- name: nginx
  image: nginx:1.19
  imagePullPolicy: IfNotPresent
  ports:
- containerPort: 80
  restartPolicy: Always